sudo: required
services:
    - docker

# things to run before running the tests
before_install:
    - docker build -f Dockerfile.dev -t shivamarora/docker-react .

# commands to run our test suite
script:
    - docker run -e CI=true shivamarora/docker-react npm run test -- --coverage

# commands to run for deployment
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-683682269864"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: 
        secure: "$AWS_ACCESS_KEY"
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
