sudo: required
services:
    - docker

# things to run before running the tests
before_install:
    - docker build -f Dockerfile.dev -t ShivamArora/docker-react .

# commands to run our test suite
script:
    - docker run -e CI=true ShivamArora/docker-react npm run test -- --coverage
